
; You may customize this and other start-up templates; 
; The location of this template is c:\emu8086\inc\0_com_template.txt

; NAME: PUNIT MIDDHA
; REGNO: 19BCE2060

DATA SEGMENT

STRING DB 'HOW ARE YOU?$'
SUBSTR DB 'AR$'
MSG1 DB 10,13,'STRING : $'
MSG2 DB 10,13,'SUBSTRING : $'
FOUND DB 10,13,'SUBSTRING IS FOUND AT POSITION : $'
NOTFOUND DB 10,13,'SUBSTRING IS NOT FOUND!$'
POS DB 0

DATA ENDS

DISPLAY MACRO MSG
MOV AH,9
LEA DX,MSG
INT 21H
ENDM    


CODE SEGMENT

ASSUME CS:CODE,DS:DATA

START:
    MOV AX,DATA
    MOV DS,AX
    DISPLAY MSG1
    DISPLAY STRING
    DISPLAY MSG2
    DISPLAY SUBSTR
    LEA SI,STRING

FIRST:
    INC POS    
    MOV AL,[SI]
    CMP AL,SUBSTR[0]    
    JE NEXT
    INC SI
    LOOP FIRST

NEXT: 
    INC SI
    MOV AL,[SI]
    CMP AL,SUBSTR[1]
    JE EQUAL

NOTEQUAL:
    MOV POS,-1
    DISPLAY NOTFOUND
    JMP EXIT

EQUAL:
    DISPLAY FOUND
    MOV DL,POS    
    ADD DL,30H    
    MOV AH,2      
    INT 21H

EXIT: MOV AH,4CH
      INT 21H

CODE ENDS

END START